### ISSUE TITLE
Connecting to Cluster not working with docker ENETUNREACH

### ISSUE THREAD

**Issue by kirrg001** [redis/node-redis#2815]
### Description

Hi!

My docker setup works great with `ioredis`, but not with `node-redis`.
(I can successfully connect to each single node with `createClient`, but `createCluster` does not work.)

```
REDIS_NODE_1: '127.0.0.1:6380',
REDIS_NODE_2: '127.0.0.1:6381',
REDIS_NODE_3: '127.0.0.1:6382',
```

```
// const redis = require('redis');  - same problem
const redis = require('@redis/client');
const cluster = redis.createCluster({
  rootNodes: [
    {
      url: `redis://${process.env.REDIS_NODE_1}`
    },
    {
      url: `redis://${process.env.REDIS_NODE_2}`
    },
    {
      url: `redis://${process.env.REDIS_NODE_3}`
    }
  ],
  defaults: {
    socket: {
      connectTimeout: 50000
    }
  }
});

[cluster].forEach(c => {
  c.on('error', err => log('Redis Cluster Error', err));
});

(async () => {
  log(`Connecting to cluster. (${process.env.REDIS_NODE_1}, ${process.env.REDIS_NODE_2}, ${process.env.REDIS_NODE_3})`);
  await cluster.connect();
  log('Connected to cluster');

  connectedToRedis = true;
})();
```

```
Redis Cluster App (7540):	Connecting to cluster. (127.0.0.1:6380, 127.0.0.1:6381, 127.0.0.1:6382)
...
Redis Cluster App (7232):	Redis Cluster Error Error: connect ENETUNREACH 172.30.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -51,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '172.30.0.2',
  port: 6379
}
```

```
$ nc -zv 127.0.0.1 6380
Connection to 127.0.0.1 port 6380 [tcp/*] succeeded!
```

```
$ docker exec -it 22917895915d redis-cli -p 6379 cluster nodes
d13eae594c1c7e6b483aacd7798ab613b8037397 172.30.0.4:6379@16379 master - 0 1723455985696 3 connected 10923-16383
44458d987c67d19dcdd673fe805533459bd1b046 172.30.0.3:6379@16379 myself,master - 0 1723455984000 2 connected 5461-10922
57e8d72cbed15e21248effe767b61ef133570a38 172.30.0.2:6379@16379 master - 0 1723455984643 1 connected 0-5460
```

```
stdout: redis-node-0-1  | Cluster correctly created
stdout: redis-node-1-1  | 1:M 12 Aug 2024 09:49:22.107 * Cluster state changed: ok
stdout: redis-node-0-1  | 89:M 12 Aug 2024 09:49:22.108 * Cluster state changed: ok
stdout: redis-node-2-1  | 1:M 12 Aug 2024 09:49:22.210 * Cluster state changed: ok
```

```
$ docker network inspect nodejs_redis-cluster-network
[
    {
        "Name": "nodejs_redis-cluster-network",
        "Id": "0f790833c4b8098627f1b6942831f264016e776722bfe7cad4d6c965de91e943",
        "Created": "2024-08-12T09:31:27.645823964Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.30.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "116560657e78e6267ed0ae50aebce2b175912da1602c3b2b3628a434f8692060": {
                "Name": "nodejs-redis-node-0-1",
                "EndpointID": "b102c8e309ec241301ec9f11bd400b630209d110059ed7f793d5693325c45882",
                "MacAddress": "02:42:ac:1e:00:02",
                "IPv4Address": "172.30.0.2/16",
                "IPv6Address": ""
            },
            "22917895915d80bfd88af52cc336c6d8d3fe14272f3898578730dae2eef7b10f": {
                "Name": "nodejs-redis-node-1-1",
                "EndpointID": "1e87aae09b68fd8d9521cdbd6033ac4069c8969413827b7cae0840e715c18855",
                "MacAddress": "02:42:ac:1e:00:03",
                "IPv4Address": "172.30.0.3/16",
                "IPv6Address": ""
            },
            "a69acfdde86e808fc1ba97afb47c7e08c0c731627d5180722bc162d81be1c9c3": {
                "Name": "nodejs-redis-node-2-1",
                "EndpointID": "9c1bda5eba16afdc1962c59774ab09f91ebf8fa1b4080120e8c44bcb2ffc66d5",
                "MacAddress": "02:42:ac:1e:00:04",
                "IPv4Address": "172.30.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "redis-cluster-network",
            "com.docker.compose.project": "nodejs",
            "com.docker.compose.version": "2.23.3"
        }
    }
]
```

```
version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=172.30.0.2:6379 172.30.0.3:6379 172.30.0.4:6379
      - REDIS_CLUSTER_CREATOR=yes
      - REDIS_CLUSTER_REPLICAS=0
      - BITNAMI_DEBUG=1
      - REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=30
    ports:
      - '6380:6379'
    networks:
      redis-cluster-network:
        ipv4_address: 172.30.0.2
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=172.30.0.2:6379 172.30.0.3:6379 172.30.0.4:6379
    ports:
      - '6381:6379'
    networks:
      redis-cluster-network:
        ipv4_address: 172.30.0.3
  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=172.30.0.2:6379 172.30.0.3:6379 172.30.0.4:6379
    ports:
      - '6382:6379'
    networks:
      redis-cluster-network:
        ipv4_address: 172.30.0.4
networks:
  redis-cluster-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
```

### Node.js Version

20.13

### Redis Server Version

docker.io/bitnami/redis-cluster:7.2

### Node Redis Version

4.7.0

### Platform

macOS

### Logs

```bash
See above.
```
